// GENERATED BY DAOX - DO NOT EDIT
import { describe, it, expect, jest, beforeEach } from '@jest/globals';
import { ConfigurationsDao } from '../../src/dao/configurations.dao.js';
import type { GenericExecutor } from '@soysouvanh/daox';

describe('ConfigurationsDao', () => {
  let mockExecutor: any;

  beforeEach(() => {
    mockExecutor = {
      query: jest.fn().mockResolvedValue([]),
      stream: jest.fn().mockReturnValue( (async function* () {})() )
    };
  });

  describe('CRUD Methods', () => {
    it('should execute insert appropriately', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await ConfigurationsDao.insert(mockExecutor, { _dummy: 1 } as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute findById', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await ConfigurationsDao.findById(mockExecutor, 1 as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute updateById', async () => {
      await ConfigurationsDao.updateById(mockExecutor, 1 as any, { _dummy: 1 } as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute deleteById', async () => {
      await ConfigurationsDao.deleteById(mockExecutor, 1 as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });
  });

  describe('Advanced Methods', () => {
    it('should execute listByCursor', async () => {
      const iterable = ConfigurationsDao.listByCursor(mockExecutor, null, 10);
      for await (const _ of iterable) {}
      expect(mockExecutor.stream).toHaveBeenCalled();
    });

    it('should execute listByOffset', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await ConfigurationsDao.listByOffset(mockExecutor, 0, 10);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute insertBatch', async () => {
      await ConfigurationsDao.insertBatch(mockExecutor, [{ _dummy: 1 } as any]);
      expect(mockExecutor.query).toHaveBeenCalled();
    });
  });
});
