// GENERATED BY DAOX - DO NOT EDIT
import { describe, it, expect, jest, beforeEach } from '@jest/globals';
import { CurrenciesDao } from '../../src/dao/currencies.dao.js';
import type { GenericExecutor } from '@soysouvanh/daox';

describe('CurrenciesDao', () => {
  let mockExecutor: any;

  beforeEach(() => {
    mockExecutor = {
      query: jest.fn().mockResolvedValue([]),
      stream: jest.fn().mockReturnValue( (async function* () {})() )
    };
  });

  describe('CRUD Methods', () => {
    it('should execute insert appropriately', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await CurrenciesDao.insert(mockExecutor, { _dummy: 1 } as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute findByCode', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await CurrenciesDao.findByCode(mockExecutor, 1 as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute updateByCode', async () => {
      await CurrenciesDao.updateByCode(mockExecutor, 1 as any, { _dummy: 1 } as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute deleteByCode', async () => {
      await CurrenciesDao.deleteByCode(mockExecutor, 1 as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });
  });

  describe('Advanced Methods', () => {
    it('should execute listByCursor', async () => {
      const iterable = CurrenciesDao.listByCursor(mockExecutor, null, 10);
      for await (const _ of iterable) {}
      expect(mockExecutor.stream).toHaveBeenCalled();
    });

    it('should execute listByOffset', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await CurrenciesDao.listByOffset(mockExecutor, 0, 10);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute insertBatch', async () => {
      await CurrenciesDao.insertBatch(mockExecutor, [{ _dummy: 1 } as any]);
      expect(mockExecutor.query).toHaveBeenCalled();
    });
  });
});
