// GENERATED BY DAOX - DO NOT EDIT
import { describe, it, expect, jest, beforeEach } from '@jest/globals';
import { Order_itemsDao } from '../../src/dao/order_items.dao.js';
import type { GenericExecutor } from '@soysouvanh/daox';

describe('Order_itemsDao', () => {
  let mockExecutor: any;

  beforeEach(() => {
    mockExecutor = {
      query: jest.fn().mockResolvedValue([]),
      stream: jest.fn().mockReturnValue( (async function* () {})() )
    };
  });

  describe('CRUD Methods', () => {
    it('should execute insert appropriately', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await Order_itemsDao.insert(mockExecutor, { "order_id": 1 } as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

  });

  describe('Advanced Methods', () => {
    it('should execute insertBatch', async () => {
      await Order_itemsDao.insertBatch(mockExecutor, [{ "order_id": 1 } as any]);
      expect(mockExecutor.query).toHaveBeenCalled();
    });
  });
});
