// GENERATED BY DAOX - DO NOT EDIT
import { describe, it, expect, jest, beforeEach } from '@jest/globals';
import { UsersDao } from '../../src/dao/users.dao.js';
import type { GenericExecutor } from '@soysouvanh/daox';

describe('UsersDao', () => {
  let mockExecutor: any;

  beforeEach(() => {
    mockExecutor = {
      query: jest.fn().mockResolvedValue([]),
      stream: jest.fn().mockReturnValue( (async function* () {})() )
    };
  });

  describe('CRUD Methods', () => {
    it('should execute insert appropriately', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await UsersDao.insert(mockExecutor, { _dummy: 1 } as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute findById', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await UsersDao.findById(mockExecutor, 1 as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute updateById', async () => {
      await UsersDao.updateById(mockExecutor, 1 as any, { _dummy: 1 } as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute deleteById', async () => {
      await UsersDao.deleteById(mockExecutor, 1 as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute findByEmail', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await UsersDao.findByEmail(mockExecutor, 1 as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute findAllByLast_nameAndFirst_name', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await UsersDao.findAllByLast_nameAndFirst_name(mockExecutor, 1 as any, 2 as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });
  });

  describe('Advanced Methods', () => {
    it('should execute listByCursor', async () => {
      const iterable = UsersDao.listByCursor(mockExecutor, null, 10);
      for await (const _ of iterable) {}
      expect(mockExecutor.stream).toHaveBeenCalled();
    });

    it('should execute listByOffset', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await UsersDao.listByOffset(mockExecutor, 0, 10);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute insertBatch', async () => {
      await UsersDao.insertBatch(mockExecutor, [{ _dummy: 1 } as any]);
      expect(mockExecutor.query).toHaveBeenCalled();
    });
  });
});
