// GENERATED BY DAOX - DO NOT EDIT
import { describe, it, expect, jest, beforeEach } from '@jest/globals';
import { User_rolesDao } from '../../src/dao/user_roles.dao.js';
import type { GenericExecutor } from '@soysouvanh/daox';

describe('User_rolesDao', () => {
  let mockExecutor: any;

  beforeEach(() => {
    mockExecutor = {
      query: jest.fn().mockResolvedValue([]),
      stream: jest.fn().mockReturnValue( (async function* () {})() )
    };
  });

  describe('CRUD Methods', () => {
    it('should execute insert appropriately', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await User_rolesDao.insert(mockExecutor, { _dummy: 1 } as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });


    it('should execute findAllByUser_id', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await User_rolesDao.findAllByUser_id(mockExecutor, 1 as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });

    it('should execute findByUser_idAndRole_name', async () => {
      mockExecutor.query.mockResolvedValueOnce([{}]);
      await User_rolesDao.findByUser_idAndRole_name(mockExecutor, 1 as any, 2 as any);
      expect(mockExecutor.query).toHaveBeenCalled();
    });
  });

  describe('Advanced Methods', () => {
    it('should execute insertBatch', async () => {
      await User_rolesDao.insertBatch(mockExecutor, [{ _dummy: 1 } as any]);
      expect(mockExecutor.query).toHaveBeenCalled();
    });
  });
});
