// GENERATED BY DAOX - DO NOT EDIT

import type { GenericExecutor } from "@soysouvanh/daox";
import { escapeIdentifier } from "@soysouvanh/daox";

export interface ConfigurationsRow {
  "id": number;
  "type": string;
  "match": string | null;
  "value": string | null;
}

export type ConfigurationsInsert = Omit<ConfigurationsRow, "id">;
export type ConfigurationsPatch = Partial<ConfigurationsInsert>;

export class ConfigurationsDao {

  static async insert(exe: GenericExecutor, data: ConfigurationsInsert): Promise<ConfigurationsRow> {
    const keys = Object.keys(data) as Array<keyof typeof data>;
    if (keys.length === 0) {
      const rows = await exe.query<ConfigurationsRow>("INSERT INTO \`configurations\` () VALUES ()");
      return rows[0] as ConfigurationsRow;
    }
    const cols = keys.map(k => escapeIdentifier("mysql", k as string)).join(", ");
    const vals = keys.map((_, i) => "?").join(", ");
    const sql = "INSERT INTO \`configurations\` (" + cols + ") VALUES (" + vals + ")";
    const params: unknown[] = keys.map(k => data[k]);
    const rows = await exe.query<ConfigurationsRow>(sql, params);
    return rows[0] as ConfigurationsRow;
  }

  static async count(exe: GenericExecutor): Promise<number> {
    const sql = "SELECT COUNT(*) as c FROM \`configurations\`";
    const rows = await exe.query<{ c: string | number | bigint }>(sql, []);
    return Number(rows[0] ? rows[0].c : 0);
  }

  static async findById(exe: GenericExecutor, pk: number): Promise<ConfigurationsRow | null> {
    const sql = "SELECT * FROM \`configurations\` WHERE \`id\` = ? LIMIT 1";
    const rows = await exe.query<ConfigurationsRow>(sql, [pk]);
    return rows.length > 0 ? rows[0] as ConfigurationsRow : null;
  }

  static async existsById(exe: GenericExecutor, pk: number): Promise<boolean> {
    const sql = "SELECT 1 AS e FROM \`configurations\` WHERE \`id\` = ? LIMIT 1";
    const rows = await exe.query<{ e: number }>(sql, [pk]);
    return rows.length > 0;
  }

  static async updateById(exe: GenericExecutor, pk: number, patch: ConfigurationsPatch): Promise<void> {
    const keys = Object.keys(patch) as Array<keyof typeof patch>;
    if (keys.length === 0) return;
    const sets = keys.map((k, i) => `${escapeIdentifier("mysql", k as string)} = ?`).join(", ");
    const pkParam = "?";
    const sql = "UPDATE \`configurations\` SET " + sets + " WHERE \`id\` = " + pkParam;
    const params: unknown[] = [...keys.map(k => patch[k]), pk];
    await exe.query<void>(sql, params);
  }

  static async deleteById(exe: GenericExecutor, pk: number): Promise<void> {
    const sql = "DELETE FROM \`configurations\` WHERE \`id\` = ?";
    await exe.query<void>(sql, [pk]);
  }

  static listByCursor(exe: GenericExecutor, lastCursor: number | null | undefined, limit: number): AsyncIterable<ConfigurationsRow> {
    if (lastCursor === null || lastCursor === undefined) {
      return exe.stream<ConfigurationsRow>("SELECT * FROM \`configurations\` ORDER BY \`id\` ASC LIMIT ?", [limit]);
    } else {
      return exe.stream<ConfigurationsRow>("SELECT * FROM \`configurations\` WHERE \`id\` > ? ORDER BY \`id\` ASC LIMIT ?", [lastCursor, limit]);
    }
  }

  static listByOffset(exe: GenericExecutor, offset: number, limit: number): Promise<ConfigurationsRow[]> {
    return exe.query<ConfigurationsRow>("SELECT * FROM \`configurations\` ORDER BY \`id\` ASC LIMIT ? OFFSET ?", [limit, offset]);
  }

  static async insertBatch(exe: GenericExecutor, items: ConfigurationsInsert[]): Promise<void> {
    if (items.length === 0) return;
    const keys = Object.keys(items[0] as unknown as Record<string, unknown>);
    const cols = keys.map(k => escapeIdentifier("mysql", k)).join(", ");
    const colCount = keys.length;
    const maxRows = Math.floor(65535 / Math.max(colCount, 1));
    for (let offset = 0; offset < items.length; offset += maxRows) {
      const chunk = items.slice(offset, offset + maxRows);
      const rowPhrases: string[] = [];
      const params: unknown[] = [];
      let pos = 1;
      for (const item of chunk) {
        const rowVals: string[] = [];
        for (const k of keys) {
          rowVals.push("?");
          params.push((item as unknown as Record<string, unknown>)[k]);
        }
        rowPhrases.push("(" + rowVals.join(", ") + ")");
      }
      const sql = "INSERT INTO \`configurations\` (" + cols + ") VALUES " + rowPhrases.join(", ");
      await exe.query<void>(sql, params);
    }
  }
}
