// GENERATED BY DAOX - DO NOT EDIT

import type { GenericExecutor } from "@soysouvanh/daox";
import { escapeIdentifier } from "@soysouvanh/daox";

export interface CurrenciesRow {
  "code": string;
  "name": string;
}

export type CurrenciesInsert = CurrenciesRow;
export type CurrenciesPatch = Partial<CurrenciesInsert>;

export class CurrenciesDao {

  static async insert(exe: GenericExecutor, data: CurrenciesInsert): Promise<CurrenciesRow> {
    const keys = Object.keys(data) as Array<keyof typeof data>;
    if (keys.length === 0) {
      const rows = await exe.query<CurrenciesRow>("INSERT INTO \`currencies\` () VALUES ()");
      return rows[0] as CurrenciesRow;
    }
    const cols = keys.map(k => escapeIdentifier("mysql", k as string)).join(", ");
    const vals = keys.map((_, i) => "?").join(", ");
    const sql = "INSERT INTO \`currencies\` (" + cols + ") VALUES (" + vals + ")";
    const params: unknown[] = keys.map(k => data[k]);
    const rows = await exe.query<CurrenciesRow>(sql, params);
    return rows[0] as CurrenciesRow;
  }

  static async count(exe: GenericExecutor): Promise<number> {
    const sql = "SELECT COUNT(*) as c FROM \`currencies\`";
    const rows = await exe.query<{ c: string | number | bigint }>(sql, []);
    return Number(rows[0] ? rows[0].c : 0);
  }

  static async findByCode(exe: GenericExecutor, pk: string): Promise<CurrenciesRow | null> {
    const sql = "SELECT * FROM \`currencies\` WHERE \`code\` = ? LIMIT 1";
    const rows = await exe.query<CurrenciesRow>(sql, [pk]);
    return rows.length > 0 ? rows[0] as CurrenciesRow : null;
  }

  static async existsByCode(exe: GenericExecutor, pk: string): Promise<boolean> {
    const sql = "SELECT 1 AS e FROM \`currencies\` WHERE \`code\` = ? LIMIT 1";
    const rows = await exe.query<{ e: number }>(sql, [pk]);
    return rows.length > 0;
  }

  static async updateByCode(exe: GenericExecutor, pk: string, patch: CurrenciesPatch): Promise<void> {
    const keys = Object.keys(patch) as Array<keyof typeof patch>;
    if (keys.length === 0) return;
    const sets = keys.map((k, i) => `${escapeIdentifier("mysql", k as string)} = ?`).join(", ");
    const pkParam = "?";
    const sql = "UPDATE \`currencies\` SET " + sets + " WHERE \`code\` = " + pkParam;
    const params: unknown[] = [...keys.map(k => patch[k]), pk];
    await exe.query<void>(sql, params);
  }

  static async deleteByCode(exe: GenericExecutor, pk: string): Promise<void> {
    const sql = "DELETE FROM \`currencies\` WHERE \`code\` = ?";
    await exe.query<void>(sql, [pk]);
  }

  static listByCursor(exe: GenericExecutor, lastCursor: string | null | undefined, limit: number): AsyncIterable<CurrenciesRow> {
    if (lastCursor === null || lastCursor === undefined) {
      return exe.stream<CurrenciesRow>("SELECT * FROM \`currencies\` ORDER BY \`code\` ASC LIMIT ?", [limit]);
    } else {
      return exe.stream<CurrenciesRow>("SELECT * FROM \`currencies\` WHERE \`code\` > ? ORDER BY \`code\` ASC LIMIT ?", [lastCursor, limit]);
    }
  }

  static listByOffset(exe: GenericExecutor, offset: number, limit: number): Promise<CurrenciesRow[]> {
    return exe.query<CurrenciesRow>("SELECT * FROM \`currencies\` ORDER BY \`code\` ASC LIMIT ? OFFSET ?", [limit, offset]);
  }

  static async insertBatch(exe: GenericExecutor, items: CurrenciesInsert[]): Promise<void> {
    if (items.length === 0) return;
    const keys = Object.keys(items[0] as unknown as Record<string, unknown>);
    const cols = keys.map(k => escapeIdentifier("mysql", k)).join(", ");
    const colCount = keys.length;
    const maxRows = Math.floor(65535 / Math.max(colCount, 1));
    for (let offset = 0; offset < items.length; offset += maxRows) {
      const chunk = items.slice(offset, offset + maxRows);
      const rowPhrases: string[] = [];
      const params: unknown[] = [];
      let pos = 1;
      for (const item of chunk) {
        const rowVals: string[] = [];
        for (const k of keys) {
          rowVals.push("?");
          params.push((item as unknown as Record<string, unknown>)[k]);
        }
        rowPhrases.push("(" + rowVals.join(", ") + ")");
      }
      const sql = "INSERT INTO \`currencies\` (" + cols + ") VALUES " + rowPhrases.join(", ");
      await exe.query<void>(sql, params);
    }
  }
}
