// GENERATED BY DAOX - DO NOT EDIT

import type { GenericExecutor } from "@soysouvanh/daox";
import { escapeIdentifier } from "@soysouvanh/daox";

export interface Order_itemsRow {
  "order_id": bigint;
  "product_id": bigint;
  "quantity": number;
}

export type Order_itemsInsert = Omit<Order_itemsRow, "quantity"> & Partial<Pick<Order_itemsRow, "quantity">>;
export type Order_itemsPatch = Partial<Order_itemsInsert>;

export class Order_itemsDao {

  static async insert(exe: GenericExecutor, data: Order_itemsInsert): Promise<Order_itemsRow> {
    const keys = Object.keys(data) as Array<keyof typeof data>;
    if (keys.length === 0) {
      const rows = await exe.query<Order_itemsRow>("INSERT INTO \`order_items\` () VALUES ()");
      return rows[0] as Order_itemsRow;
    }
    const cols = keys.map(k => escapeIdentifier("mysql", k as string)).join(", ");
    const vals = keys.map((_, i) => "?").join(", ");
    const sql = "INSERT INTO \`order_items\` (" + cols + ") VALUES (" + vals + ")";
    const params: unknown[] = keys.map(k => data[k]);
    const rows = await exe.query<Order_itemsRow>(sql, params);
    return rows[0] as Order_itemsRow;
  }

  static async count(exe: GenericExecutor): Promise<number> {
    const sql = "SELECT COUNT(*) as c FROM \`order_items\`";
    const rows = await exe.query<{ c: string | number | bigint }>(sql, []);
    return Number(rows[0] ? rows[0].c : 0);
  }

  static async insertBatch(exe: GenericExecutor, items: Order_itemsInsert[]): Promise<void> {
    if (items.length === 0) return;
    const keys = Object.keys(items[0] as unknown as Record<string, unknown>);
    const cols = keys.map(k => escapeIdentifier("mysql", k)).join(", ");
    const colCount = keys.length;
    const maxRows = Math.floor(65535 / Math.max(colCount, 1));
    for (let offset = 0; offset < items.length; offset += maxRows) {
      const chunk = items.slice(offset, offset + maxRows);
      const rowPhrases: string[] = [];
      const params: unknown[] = [];
      let pos = 1;
      for (const item of chunk) {
        const rowVals: string[] = [];
        for (const k of keys) {
          rowVals.push("?");
          params.push((item as unknown as Record<string, unknown>)[k]);
        }
        rowPhrases.push("(" + rowVals.join(", ") + ")");
      }
      const sql = "INSERT INTO \`order_items\` (" + cols + ") VALUES " + rowPhrases.join(", ");
      await exe.query<void>(sql, params);
    }
  }
}
