// GENERATED BY DAOX - DO NOT EDIT

import type { GenericExecutor } from "@soysouvanh/daox";
import { escapeIdentifier } from "@soysouvanh/daox";

export interface Product_metadataRow {
  "id": Buffer;
  "category": string;
  "attributes": Record<string, unknown> | unknown[] | null;
  "raw_data": Buffer | null;
}

export type Product_metadataInsert = Product_metadataRow;
export type Product_metadataPatch = Partial<Product_metadataInsert>;

export class Product_metadataDao {
  private static readonly _VALID_COLS = new Set(["id","category","attributes","raw_data"]);

  static async insert(exe: GenericExecutor, data: Product_metadataInsert): Promise<Product_metadataRow> {
    const keys = Object.keys(data).filter(k => Product_metadataDao._VALID_COLS.has(k)) as Array<keyof typeof data>;
    if (keys.length === 0) {
      const rows = await exe.query<Product_metadataRow>("INSERT INTO \`product_metadata\` () VALUES ()");
      return rows[0] as Product_metadataRow;
    }
    const cols = keys.map(k => escapeIdentifier("mysql", k as string)).join(", ");
    const vals = keys.map((_, i) => "?").join(", ");
    const sql = "INSERT INTO \`product_metadata\` (" + cols + ") VALUES (" + vals + ")";
    const params: unknown[] = keys.map(k => data[k]);
    const rows = await exe.query<Product_metadataRow>(sql, params);
    return rows[0] as Product_metadataRow;
  }

  static async count(exe: GenericExecutor): Promise<number> {
    const sql = "SELECT COUNT(*) as c FROM \`product_metadata\`";
    const rows = await exe.query<{ c: string | number | bigint }>(sql, []);
    return Number(rows[0] ? rows[0].c : 0);
  }

  static async findById(exe: GenericExecutor, pk: Buffer): Promise<Product_metadataRow | null> {
    const sql = "SELECT * FROM \`product_metadata\` WHERE \`id\` = ? LIMIT 1";
    const rows = await exe.query<Product_metadataRow>(sql, [pk]);
    return rows.length > 0 ? rows[0] as Product_metadataRow : null;
  }

  static async existsById(exe: GenericExecutor, pk: Buffer): Promise<boolean> {
    const sql = "SELECT 1 AS e FROM \`product_metadata\` WHERE \`id\` = ? LIMIT 1";
    const rows = await exe.query<{ e: number }>(sql, [pk]);
    return rows.length > 0;
  }

  static async updateById(exe: GenericExecutor, pk: Buffer, patch: Product_metadataPatch): Promise<void> {
    const keys = Object.keys(patch).filter(k => Product_metadataDao._VALID_COLS.has(k)) as Array<keyof typeof patch>;
    if (keys.length === 0) return;
    const sets = keys.map((k, i) => `${escapeIdentifier("mysql", k as string)} = ?`).join(", ");
    const pkParam = "?";
    const sql = "UPDATE \`product_metadata\` SET " + sets + " WHERE \`id\` = " + pkParam;
    const params: unknown[] = [...keys.map(k => patch[k]), pk];
    await exe.query<void>(sql, params);
  }

  static async deleteById(exe: GenericExecutor, pk: Buffer): Promise<void> {
    const sql = "DELETE FROM \`product_metadata\` WHERE \`id\` = ?";
    await exe.query<void>(sql, [pk]);
  }

  static listByCursor(exe: GenericExecutor, lastCursor: Buffer | null | undefined, limit: number): AsyncIterable<Product_metadataRow> {
    if (lastCursor === null || lastCursor === undefined) {
      return exe.stream<Product_metadataRow>("SELECT * FROM \`product_metadata\` ORDER BY \`id\` ASC LIMIT ?", [limit]);
    } else {
      return exe.stream<Product_metadataRow>("SELECT * FROM \`product_metadata\` WHERE \`id\` > ? ORDER BY \`id\` ASC LIMIT ?", [lastCursor, limit]);
    }
  }

  static listByOffset(exe: GenericExecutor, offset: number, limit: number): Promise<Product_metadataRow[]> {
    return exe.query<Product_metadataRow>("SELECT * FROM \`product_metadata\` ORDER BY \`id\` ASC LIMIT ? OFFSET ?", [limit, offset]);
  }

  static async insertBatch(exe: GenericExecutor, items: Product_metadataInsert[]): Promise<void> {
    if (items.length === 0) return;
    const keys = Object.keys(items[0] as unknown as Record<string, unknown>).filter(k => Product_metadataDao._VALID_COLS.has(k));
    if (keys.length === 0) return;
    const cols = keys.map(k => escapeIdentifier("mysql", k)).join(", ");
    const colCount = keys.length;
    const maxRows = Math.floor(65535 / Math.max(colCount, 1));
    for (let offset = 0; offset < items.length; offset += maxRows) {
      const chunk = items.slice(offset, offset + maxRows);
      const rowPhrases: string[] = [];
      const params: unknown[] = [];
      let pos = 1;
      for (const item of chunk) {
        const rowVals: string[] = [];
        for (const k of keys) {
          rowVals.push("?");
          params.push((item as unknown as Record<string, unknown>)[k]);
        }
        rowPhrases.push("(" + rowVals.join(", ") + ")");
      }
      const sql = "INSERT INTO \`product_metadata\` (" + cols + ") VALUES " + rowPhrases.join(", ");
      await exe.query<void>(sql, params);
    }
  }
}
