// GENERATED BY DAOX - DO NOT EDIT

import type { GenericExecutor } from "@soysouvanh/daox";
import { escapeIdentifier } from "@soysouvanh/daox";

export interface User_rolesRow {
  "user_id": bigint;
  "role_name": string;
  "assigned_at": Date | null;
}

export type User_rolesInsert = Omit<User_rolesRow, "assigned_at"> & Partial<Pick<User_rolesRow, "assigned_at">>;
export type User_rolesPatch = Partial<User_rolesInsert>;

export class User_rolesDao {

  static async insert(exe: GenericExecutor, data: User_rolesInsert): Promise<User_rolesRow> {
    const keys = Object.keys(data) as Array<keyof typeof data>;
    if (keys.length === 0) {
      const rows = await exe.query<User_rolesRow>("INSERT INTO \`user_roles\` () VALUES ()");
      return rows[0] as User_rolesRow;
    }
    const cols = keys.map(k => escapeIdentifier("mysql", k as string)).join(", ");
    const vals = keys.map((_, i) => "?").join(", ");
    const sql = "INSERT INTO \`user_roles\` (" + cols + ") VALUES (" + vals + ")";
    const params: unknown[] = keys.map(k => data[k]);
    const rows = await exe.query<User_rolesRow>(sql, params);
    return rows[0] as User_rolesRow;
  }

  static async count(exe: GenericExecutor): Promise<number> {
    const sql = "SELECT COUNT(*) as c FROM \`user_roles\`";
    const rows = await exe.query<{ c: string | number | bigint }>(sql, []);
    return Number(rows[0] ? rows[0].c : 0);
  }

  static async existsByUser_id(exe: GenericExecutor, user_id: bigint): Promise<boolean> {
    const sql = "SELECT 1 AS e FROM \`user_roles\` WHERE \`user_id\` = ? LIMIT 1";
    const rows = await exe.query<{ e: number }>(sql, [user_id]);
    return rows.length > 0;
  }

  static async findAllByUser_id(exe: GenericExecutor, user_id: bigint): Promise<User_rolesRow[]> {
    const sql = "SELECT * FROM \`user_roles\` WHERE \`user_id\` = ?";
    const rows = await exe.query<User_rolesRow>(sql, [user_id]);
    return rows;
  }

  static async countByUser_id(exe: GenericExecutor, user_id: bigint): Promise<number> {
    const sql = "SELECT COUNT(*) as c FROM \`user_roles\` WHERE \`user_id\` = ?";
    const rows = await exe.query<{ c: string | number | bigint }>(sql, [user_id]);
    return Number(rows[0] ? rows[0].c : 0);
  }

  static async existsByUser_idAndRole_name(exe: GenericExecutor, user_id: bigint, role_name: string): Promise<boolean> {
    const sql = "SELECT 1 AS e FROM \`user_roles\` WHERE \`user_id\` = ? AND \`role_name\` = ? LIMIT 1";
    const rows = await exe.query<{ e: number }>(sql, [user_id, role_name]);
    return rows.length > 0;
  }

  static async findByUser_idAndRole_name(exe: GenericExecutor, user_id: bigint, role_name: string): Promise<User_rolesRow | null> {
    const sql = "SELECT * FROM \`user_roles\` WHERE \`user_id\` = ? AND \`role_name\` = ? LIMIT 1";
    const rows = await exe.query<User_rolesRow>(sql, [user_id, role_name]);
    return rows.length > 0 ? rows[0] as User_rolesRow : null;
  }


  static async insertBatch(exe: GenericExecutor, items: User_rolesInsert[]): Promise<void> {
    if (items.length === 0) return;
    const keys = Object.keys(items[0] as unknown as Record<string, unknown>);
    const cols = keys.map(k => escapeIdentifier("mysql", k)).join(", ");
    const colCount = keys.length;
    const maxRows = Math.floor(65535 / Math.max(colCount, 1));
    for (let offset = 0; offset < items.length; offset += maxRows) {
      const chunk = items.slice(offset, offset + maxRows);
      const rowPhrases: string[] = [];
      const params: unknown[] = [];
      let pos = 1;
      for (const item of chunk) {
        const rowVals: string[] = [];
        for (const k of keys) {
          rowVals.push("?");
          params.push((item as unknown as Record<string, unknown>)[k]);
        }
        rowPhrases.push("(" + rowVals.join(", ") + ")");
      }
      const sql = "INSERT INTO \`user_roles\` (" + cols + ") VALUES " + rowPhrases.join(", ");
      await exe.query<void>(sql, params);
    }
  }
}
