// GENERATED BY DAOX - DO NOT EDIT

import type { GenericExecutor } from "@soysouvanh/daox";
import { escapeIdentifier } from "@soysouvanh/daox";

export interface UsersRow {
  "id": bigint;
  "email": string;
  "first_name": string | null;
  "last_name": string;
  "status": string;
  "created_at": Date | null;
}

export type UsersInsert = Omit<UsersRow, "id" | "status" | "created_at"> & Partial<Pick<UsersRow, "status" | "created_at">>;
export type UsersPatch = Partial<UsersInsert>;

export class UsersDao {

  static async insert(exe: GenericExecutor, data: UsersInsert): Promise<UsersRow> {
    const keys = Object.keys(data) as Array<keyof typeof data>;
    if (keys.length === 0) {
      const rows = await exe.query<UsersRow>("INSERT INTO \`users\` () VALUES ()");
      return rows[0] as UsersRow;
    }
    const cols = keys.map(k => escapeIdentifier("mysql", k as string)).join(", ");
    const vals = keys.map((_, i) => "?").join(", ");
    const sql = "INSERT INTO \`users\` (" + cols + ") VALUES (" + vals + ")";
    const params: unknown[] = keys.map(k => data[k]);
    const rows = await exe.query<UsersRow>(sql, params);
    return rows[0] as UsersRow;
  }

  static async count(exe: GenericExecutor): Promise<number> {
    const sql = "SELECT COUNT(*) as c FROM \`users\`";
    const rows = await exe.query<{ c: string | number | bigint }>(sql, []);
    return Number(rows[0] ? rows[0].c : 0);
  }

  static async findById(exe: GenericExecutor, pk: bigint): Promise<UsersRow | null> {
    const sql = "SELECT * FROM \`users\` WHERE \`id\` = ? LIMIT 1";
    const rows = await exe.query<UsersRow>(sql, [pk]);
    return rows.length > 0 ? rows[0] as UsersRow : null;
  }

  static async existsById(exe: GenericExecutor, pk: bigint): Promise<boolean> {
    const sql = "SELECT 1 AS e FROM \`users\` WHERE \`id\` = ? LIMIT 1";
    const rows = await exe.query<{ e: number }>(sql, [pk]);
    return rows.length > 0;
  }

  static async updateById(exe: GenericExecutor, pk: bigint, patch: UsersPatch): Promise<void> {
    const keys = Object.keys(patch) as Array<keyof typeof patch>;
    if (keys.length === 0) return;
    const sets = keys.map((k, i) => `${escapeIdentifier("mysql", k as string)} = ?`).join(", ");
    const pkParam = "?";
    const sql = "UPDATE \`users\` SET " + sets + " WHERE \`id\` = " + pkParam;
    const params: unknown[] = [...keys.map(k => patch[k]), pk];
    await exe.query<void>(sql, params);
  }

  static async deleteById(exe: GenericExecutor, pk: bigint): Promise<void> {
    const sql = "DELETE FROM \`users\` WHERE \`id\` = ?";
    await exe.query<void>(sql, [pk]);
  }

  static async existsByEmail(exe: GenericExecutor, email: string): Promise<boolean> {
    const sql = "SELECT 1 AS e FROM \`users\` WHERE \`email\` = ? LIMIT 1";
    const rows = await exe.query<{ e: number }>(sql, [email]);
    return rows.length > 0;
  }

  static async findByEmail(exe: GenericExecutor, email: string): Promise<UsersRow | null> {
    const sql = "SELECT * FROM \`users\` WHERE \`email\` = ? LIMIT 1";
    const rows = await exe.query<UsersRow>(sql, [email]);
    return rows.length > 0 ? rows[0] as UsersRow : null;
  }

  static async existsByLast_nameAndFirst_name(exe: GenericExecutor, last_name: string, first_name: string | null): Promise<boolean> {
    const sql = "SELECT 1 AS e FROM \`users\` WHERE \`last_name\` = ? AND \`first_name\` = ? LIMIT 1";
    const rows = await exe.query<{ e: number }>(sql, [last_name, first_name]);
    return rows.length > 0;
  }

  static async findAllByLast_nameAndFirst_name(exe: GenericExecutor, last_name: string, first_name: string | null): Promise<UsersRow[]> {
    const sql = "SELECT * FROM \`users\` WHERE \`last_name\` = ? AND \`first_name\` = ?";
    const rows = await exe.query<UsersRow>(sql, [last_name, first_name]);
    return rows;
  }

  static async countByLast_nameAndFirst_name(exe: GenericExecutor, last_name: string, first_name: string | null): Promise<number> {
    const sql = "SELECT COUNT(*) as c FROM \`users\` WHERE \`last_name\` = ? AND \`first_name\` = ?";
    const rows = await exe.query<{ c: string | number | bigint }>(sql, [last_name, first_name]);
    return Number(rows[0] ? rows[0].c : 0);
  }


  static listByCursor(exe: GenericExecutor, lastCursor: bigint | null | undefined, limit: number): AsyncIterable<UsersRow> {
    if (lastCursor === null || lastCursor === undefined) {
      return exe.stream<UsersRow>("SELECT * FROM \`users\` ORDER BY \`id\` ASC LIMIT ?", [limit]);
    } else {
      return exe.stream<UsersRow>("SELECT * FROM \`users\` WHERE \`id\` > ? ORDER BY \`id\` ASC LIMIT ?", [lastCursor, limit]);
    }
  }

  static listByOffset(exe: GenericExecutor, offset: number, limit: number): Promise<UsersRow[]> {
    return exe.query<UsersRow>("SELECT * FROM \`users\` ORDER BY \`id\` ASC LIMIT ? OFFSET ?", [limit, offset]);
  }

  static async insertBatch(exe: GenericExecutor, items: UsersInsert[]): Promise<void> {
    if (items.length === 0) return;
    const keys = Object.keys(items[0] as unknown as Record<string, unknown>);
    const cols = keys.map(k => escapeIdentifier("mysql", k)).join(", ");
    const colCount = keys.length;
    const maxRows = Math.floor(65535 / Math.max(colCount, 1));
    for (let offset = 0; offset < items.length; offset += maxRows) {
      const chunk = items.slice(offset, offset + maxRows);
      const rowPhrases: string[] = [];
      const params: unknown[] = [];
      let pos = 1;
      for (const item of chunk) {
        const rowVals: string[] = [];
        for (const k of keys) {
          rowVals.push("?");
          params.push((item as unknown as Record<string, unknown>)[k]);
        }
        rowPhrases.push("(" + rowVals.join(", ") + ")");
      }
      const sql = "INSERT INTO \`users\` (" + cols + ") VALUES " + rowPhrases.join(", ");
      await exe.query<void>(sql, params);
    }
  }
}
