#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { assertMemoryBounds } from '../introspection/guard.js';
import { validateOutputDir } from './io_guard.js';
import { buildTableInterfaces, buildCrudMethods, buildAdvancedMethods, mapSqlTypeToTs } from '../generator/index.js';

/**
 * =========================================================================
 * DAOX COMMAND LINE PIPELINE (AOT COMPILER)
 * =========================================================================
 * Root entry point for the complete Daox introspection-to-generation flow.
 * Processes the raw topological schema extracted from the designated database,
 * enforces memory bounds, and translates it into strictly typed TypeScript DAO files.
 */

// CLI parsing
const args = process.argv.slice(2);
const command = args[0];

if (command !== 'generate') {
  console.error('Usage: npx @soysouvanh/daox generate --url="<DB_URL>" [--out-dir="./src/dao/"]');
  process.exit(1);
}

let url = '';
let outDir = '';

for (const arg of args.slice(1)) {
  if (arg.startsWith('--url=')) url = arg.slice(6).replace(/^"|"$/g, '');
  if (arg.startsWith('--out-dir=')) outDir = arg.slice(10).replace(/^"|"$/g, '');
}

if (!url) {
  console.error('Missing --url');
  process.exit(1);
}
if (!outDir) {
  outDir = './src/dao/';
}

/**
 * Detects the database dialect from the URL.
 * Enforces Anti-SSRF by rejecting unknown protocols (Tache 5.4).
 */
function detectDialect(dbUrl: string): string {
  if (dbUrl.startsWith('postgres://') || dbUrl.startsWith('postgresql://')) return 'postgres';
  if (dbUrl.startsWith('mysql://')) return 'mysql';
  if (dbUrl.startsWith('oracle://') || dbUrl.startsWith('oracledb://')) return 'oracle';
  if (dbUrl.startsWith('sqlserver://') || dbUrl.startsWith('mssql://')) return 'mssql';
  if (dbUrl.endsWith('.db') || dbUrl.endsWith('.sqlite') || dbUrl.startsWith('sqlite://')) return 'sqlite';
  throw new Error('SECURITY: Unsupported or unrecognized DB URL dialect');
}

async function main(): Promise<void> {
  const dialect = detectDialect(url);
  console.log(`Detecting ${dialect} schema...`);
  
  let schema;
  if (dialect === 'postgres') {
    const { scanPostgres } = await import('../introspection/postgres_scanner.js');
    schema = await scanPostgres(url);
  } else if (dialect === 'mysql') {
    const { scanMysql } = await import('../introspection/mysql_scanner.js');
    schema = await scanMysql(url);
  } else if (dialect === 'oracle') {
    const { scanOracle } = await import('../introspection/oracle_scanner.js');
    schema = await scanOracle(url);
  } else if (dialect === 'mssql') {
    const { scanSqlServer } = await import('../introspection/sqlserver_scanner.js');
    schema = await scanSqlServer(url);
  } else if (dialect === 'sqlite') {
    const { scanSqlite } = await import('../introspection/sqlite_scanner.js');
    schema = await scanSqlite(url);
  } else {
    throw new Error('Dialect not implemented');
  }

  assertMemoryBounds(schema);

  console.log(`Schema extracted: ${schema.tables.length} tables.`);

  // Generated header: NO @ts-nocheck (Rule 4 - Typage absolu)
  const header = '// GENERATED BY DAOX - DO NOT EDIT\n\nimport type { GenericExecutor } from "@soysouvanh/daox";\nimport { escapeIdentifier } from "@soysouvanh/daox";\n\n';

  const finalOutDir = validateOutputDir(outDir, process.cwd());
  if (!fs.existsSync(finalOutDir)) {
    fs.mkdirSync(finalOutDir, { recursive: true });
  } else {
    // Clean previously generated files (deterministic output)
    const files = fs.readdirSync(finalOutDir);
    for (const file of files) {
      if (file.endsWith('.dao.ts') || file.endsWith('.dao.js') || file === 'index.ts' || file === 'index.js') {
        fs.unlinkSync(path.join(finalOutDir, file));
      }
    }
  }
  
  let indexContent = '// GENERATED BY DAOX - DO NOT EDIT\n\n';
  
  for (const t of schema.tables) {
    for (const c of t.columns) {
      c.typeLocal = mapSqlTypeToTs(dialect, c.sqlType);
    }
    
    const safeTable = t.name.replace(/[^a-zA-Z0-9_$]/g, '_');
    const entity = safeTable.charAt(0).toUpperCase() + safeTable.slice(1);
    
    let tableContent = header;
    tableContent += buildTableInterfaces(t) + '\n';
    tableContent += 'export class ' + entity + 'Dao {\n';
    tableContent += buildCrudMethods(dialect, t) + '\n';
    tableContent += buildAdvancedMethods(dialect, t) + '\n';
    tableContent += '}\n';
    
    const tableFilePath = path.join(finalOutDir, safeTable + '.dao.ts');
    fs.writeFileSync(tableFilePath, tableContent);
    console.log('  -> Table "' + t.name + '" processed.');
    
    indexContent += "export * from './" + safeTable + ".dao.js';\n";
  }
  
  const indexFilePath = path.join(finalOutDir, 'index.ts');
  fs.writeFileSync(indexFilePath, indexContent);
  console.log('Code successfully generated at ' + finalOutDir);
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
