import { DatabaseSchema } from '../introspection/types.js';

export function buildSchemaRegistry(schema: DatabaseSchema): string {
  let content = `// GENERATED BY DAOX - DO NOT EDIT\n`;
  content += `// AOT Database Schema Registry for LightX validation and OpenAPI\n\n`;
  
  content += `export const DaoxSchemaRegistry = {\n`;
  content += `  tables: {\n`;
  
  for (const t of schema.tables) {
    if (t.name === '__proto__' || t.name === 'constructor') continue;
    const escapedTable = JSON.stringify(t.name);
    content += `    ${escapedTable}: {\n`;
    content += `      name: ${escapedTable},\n`;
    content += `      primaryKeys: ${JSON.stringify(t.primaryKeys)},\n`;
    content += `      columns: {\n`;
    
    for (const c of t.columns) {
      if (c.name === '__proto__' || c.name === 'constructor') continue;
      const escapedCol = JSON.stringify(c.name);
      content += `        ${escapedCol}: {\n`;
      content += `          name: ${escapedCol},\n`;
      content += `          sqlType: ${JSON.stringify(c.sqlType)},\n`;
      content += `          typeLocal: ${JSON.stringify(c.typeLocal)},\n`;
      content += `          isNullable: ${c.isNullable},\n`;
      content += `          hasDefault: ${c.hasDefault},\n`;
      content += `          isAutoIncrement: ${c.isAutoIncrement},\n`;
      content += `          minLength: ${c.minLength !== undefined ? c.minLength : 'undefined'},\n`;
      content += `          maxLength: ${c.maxLength !== undefined ? c.maxLength : 'undefined'},\n`;
      content += `          minValue: ${c.minValue !== undefined ? c.minValue : 'undefined'},\n`;
      content += `          maxValue: ${c.maxValue !== undefined ? c.maxValue : 'undefined'},\n`;
      content += `          format: ${c.format ? JSON.stringify(c.format) : 'undefined'},\n`;
      content += `          enumValues: ${c.enumValues ? JSON.stringify(c.enumValues) : 'undefined'},\n`;
      content += `          businessRules: ${c.businessRules ? JSON.stringify(c.businessRules) : 'undefined'}\n`;
      content += `        },\n`;
    }
    content += `      },\n`;
    content += `      indexes: ${JSON.stringify(t.indexes)}\n`;
    content += `    },\n`;
  }
  
  content += `  }\n`;
  content += `} as const;\n\n`;
  
  content += `export type DaoxRegistryType = typeof DaoxSchemaRegistry;\n`;

  return content;
}
