import { TableSchema } from '../introspection/types.js';
import { toSafeTsIdentifier } from './escape.js';

export function buildDaoTests(dialect: string, table: TableSchema, importPath: string = '.'): string {
  const safeTable = toSafeTsIdentifier(table.name, 'table');
  const entity = safeTable.charAt(0).toUpperCase() + safeTable.slice(1);
  const pkName = table.primaryKeys.length === 1 ? table.primaryKeys[0] : null;
  const PkTitle = pkName ? (pkName.charAt(0).toUpperCase() + pkName.slice(1)) : 'Pk';
  const dummyCol = table.columns.length > 0 ? table.columns[0]!.name : '_dummy';

  let code = `// GENERATED BY DAOX - DO NOT EDIT\n`;
  code += `import { describe, it, expect, jest, beforeEach } from '@jest/globals';\n`;
  code += `import { ${entity}Dao } from '${importPath}/${safeTable}.dao.js';\n`;
  code += `import type { GenericExecutor } from '@soysouvanh/daox';\n\n`;
  code += `describe('${entity}Dao', () => {\n`;
  code += `  let mockExecutor: any;\n\n`;
  code += `  beforeEach(() => {\n`;
  code += `    mockExecutor = {\n`;
  code += `      query: jest.fn().mockResolvedValue([]),\n`;
  code += `      stream: jest.fn().mockReturnValue( (async function* () {})() )\n`;
  code += `    };\n`;
  code += `  });\n\n`;

  code += `  describe('CRUD Methods', () => {\n`;
  code += `    it('should execute insert appropriately', async () => {\n`;
  code += `      mockExecutor.query.mockResolvedValueOnce([{}]);\n`;
  code += `      await ${entity}Dao.insert(mockExecutor, { "${dummyCol}": 1 } as any);\n`;
  code += `      expect(mockExecutor.query).toHaveBeenCalled();\n`;
  code += `    });\n\n`;

  if (pkName) {
    code += `    it('should execute findBy${PkTitle}', async () => {\n`;
    code += `      mockExecutor.query.mockResolvedValueOnce([{}]);\n`;
    code += `      await ${entity}Dao.findBy${PkTitle}(mockExecutor, 1 as any);\n`;
    code += `      expect(mockExecutor.query).toHaveBeenCalled();\n`;
    code += `    });\n\n`;

    code += `    it('should execute updateBy${PkTitle}', async () => {\n`;
    code += `      await ${entity}Dao.updateBy${PkTitle}(mockExecutor, 1 as any, { "${dummyCol}": 1 } as any);\n`;
    code += `      expect(mockExecutor.query).toHaveBeenCalled();\n`;
    code += `    });\n\n`;

    code += `    it('should execute deleteBy${PkTitle}', async () => {\n`;
    code += `      await ${entity}Dao.deleteBy${PkTitle}(mockExecutor, 1 as any);\n`;
    code += `      expect(mockExecutor.query).toHaveBeenCalled();\n`;
    code += `    });\n`;
  }

  const validIndexes = (table.indexes || []).filter(idx =>
    !(idx.columns.length === 1 && idx.columns[0] === pkName)
  );

  for (const idx of validIndexes) {
    const colsTitle = idx.columns.map(c => c.charAt(0).toUpperCase() + c.slice(1)).join('And');
    const colsArgs = idx.columns.map((_, i) => `${i + 1} as any`).join(', ');

    if (idx.isUnique) {
      code += `\n    it('should execute findBy${colsTitle}', async () => {\n`;
      code += `      mockExecutor.query.mockResolvedValueOnce([{}]);\n`;
      code += `      await ${entity}Dao.findBy${colsTitle}(mockExecutor, ${colsArgs});\n`;
      code += `      expect(mockExecutor.query).toHaveBeenCalled();\n`;
      code += `    });\n`;
    } else {
      code += `\n    it('should execute findAllBy${colsTitle}', async () => {\n`;
      code += `      mockExecutor.query.mockResolvedValueOnce([{}]);\n`;
      code += `      await ${entity}Dao.findAllBy${colsTitle}(mockExecutor, ${colsArgs});\n`;
      code += `      expect(mockExecutor.query).toHaveBeenCalled();\n`;
      code += `    });\n`;
    }
  }
  code += `  });\n\n`;

  code += `  describe('Advanced Methods', () => {\n`;
  if (pkName) {
    code += `    it('should execute listByCursor', async () => {\n`;
    code += `      const iterable = ${entity}Dao.listByCursor(mockExecutor, null, 10);\n`;
    code += `      for await (const _ of iterable) {}\n`;
    code += `      expect(mockExecutor.stream).toHaveBeenCalled();\n`;
    code += `    });\n\n`;

    code += `    it('should execute listByOffset', async () => {\n`;
    code += `      mockExecutor.query.mockResolvedValueOnce([{}]);\n`;
    code += `      await ${entity}Dao.listByOffset(mockExecutor, 0, 10);\n`;
    code += `      expect(mockExecutor.query).toHaveBeenCalled();\n`;
    code += `    });\n\n`;
  }

  code += `    it('should execute insertBatch', async () => {\n`;
  code += `      await ${entity}Dao.insertBatch(mockExecutor, [{ "${dummyCol}": 1 } as any]);\n`;
  code += `      expect(mockExecutor.query).toHaveBeenCalled();\n`;
  code += `    });\n`;
  code += `  });\n`;

  code += `});\n`;

  return code;
}
