// GENERATED BY @soysouvanh/tmplx - DO NOT EDIT
import type { Writable } from "node:stream";
import { escapeHtml } from "@soysouvanh/tmplx";

// EXTREME BARE METAL : Pre-encoded UTF-8 memory pointers
const _S0 = Buffer.from("<div>Partial ", "utf8");
const _S1 = Buffer.from("</div>\n", "utf8");
const _S2 = Buffer.from("<h1>Hello</h1>\n<div>Partial ", "utf8");
const _S3 = Buffer.from("</div>\n  default \n<ul>\n", "utf8");
const _S4 = Buffer.from("\n  <li>", "utf8");
const _S5 = Buffer.from("</li>\n", "utf8");
const _S6 = Buffer.from("\n</ul>\n", "utf8");

export function render_partial<T extends Record<string, any>>(out: Writable, view_data: T): void {
      out.write(_S0);
      // XSS-vector warning: Raw print used
      out.write(String(view_data.raw));
      out.write(_S1);
}

export function render_test<T extends Record<string, any>>(out: Writable, view_data: T): void {
      out.write(_S2);
      // XSS-vector warning: Raw print used
      out.write(String(view_data.raw));
      out.write(_S3);
      for (const item of view_data.items) {
      out.write(_S4);
      out.write(escapeHtml(item.name));
      out.write(_S5);
      }
      out.write(_S6);
}

