import fs from "node:fs";
import path from "node:path";
import { resolveDependencies } from "../compiler/resolver.ts";
import { buildTemplateFunction } from "../compiler/generator.ts";

export function runCLI(args: string[]) {
  if (args[0] !== "build") {
    console.error("Usage: tmplx build --in <dir> --out <file>");
    process.exit(1);
  }

  let inDir = "./templates";
  let outFile = "./src/tmplx_generated.ts";

  for (let i = 1; i < args.length; i++) {
    if (args[i] === "--in") {
      if (i + 1 >= args.length) {
        console.error("Missing directory path for --in");
        process.exit(1);
      }
      inDir = args[++i];
    } else if (args[i] === "--out") {
      if (i + 1 >= args.length) {
        console.error("Missing file path for --out");
        process.exit(1);
      }
      outFile = args[++i];
    }
  }

  if (!outFile.endsWith(".ts") && !outFile.endsWith(".js")) {
    console.error("Output compiler file must end with .ts or .js");
    process.exit(1);
  }

  const rootDir = path.resolve(process.cwd(), inDir);
  const outPath = path.resolve(process.cwd(), outFile);

  if (!fs.existsSync(rootDir) || !fs.statSync(rootDir).isDirectory()) {
    console.error(`Input directory does not exist or is not a directory: ${rootDir}`);
    process.exit(1);
  }

  function getAllHtmlFiles(dir: string, fileList: string[] = [], basePath: string = ""): string[] {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory() && !entry.name.startsWith("_")) {
        getAllHtmlFiles(path.join(dir, entry.name), fileList, path.join(basePath, entry.name));
      } else if (entry.isFile() && entry.name.endsWith(".html") && !entry.name.startsWith("_")) {
        fileList.push(path.join(basePath, entry.name));
      }
    }
    return fileList;
  }

  const files = getAllHtmlFiles(rootDir);
  
  const staticsMap = new Map<string, number>();
  let functionsCode = "";

  const usedFuncNames = new Set<string>();

  for (const relativePath of files) {
    const filePath = path.join(rootDir, relativePath);
    try {
      const tokens = resolveDependencies(filePath, rootDir);
      // Ensure unique name natively preventing collisions between `users-profile` and `users/profile`
      const funcName = "render_" + relativePath.replace(/[^a-zA-Z0-9]/g, "_").replace(/_html$/i, "");
      
      if (usedFuncNames.has(funcName)) {
        throw new Error(`COLLISION ERROR: The generated function name '${funcName}' conflicts with another template. Please rename the file or folder.`);
      }
      usedFuncNames.add(funcName);

      functionsCode += buildTemplateFunction(funcName, tokens, staticsMap) + "\n";
    } catch (err) {
      console.error(`Error compiling ${relativePath}:`, err);
      process.exit(1);
    }
  }

  const staticDecls = Array.from(staticsMap.entries())
    // Sorting by ID to ensure _S0, _S1, etc. align correctly
    .sort((a, b) => a[1] - b[1])
    .map(([buf, i]) => `const _S${i} = Buffer.from(${JSON.stringify(buf)}, "utf8");`)
    .join("\n");

  const finalOutput = `// GENERATED BY @soysouvanh/tmplx - DO NOT EDIT
import type { Writable } from "node:stream";
import { escapeHtml } from "@soysouvanh/tmplx";

// EXTREME BARE METAL : Pre-encoded UTF-8 memory pointers
${staticDecls}

${functionsCode}`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, finalOutput, "utf8");
  console.log(`Successfully built ${files.length} template(s) to ${outPath}`);
}
