// GENERATED BY DAOX - DO NOT EDIT

import type { GenericExecutor } from "@soysouvanh/daox";
import { escapeIdentifier } from "@soysouvanh/daox";

export interface Active_usersRow {
  "id": bigint | null;
  "email": string | null;
  "first_name": string | null;
  "last_name": string | null;
}

export type Active_usersInsert = Active_usersRow;
export type Active_usersPatch = Partial<Active_usersInsert>;

export class Active_usersDao {
  static listByCursor(exe: GenericExecutor, lastCursor: bigint | null | undefined, limit: number): AsyncIterable<Active_usersRow> {
    if (lastCursor === null || lastCursor === undefined) {
      return exe.stream<Active_usersRow>("SELECT * FROM \`active_users\` ORDER BY \`id\` ASC LIMIT ?", [limit]);
    } else {
      return exe.stream<Active_usersRow>("SELECT * FROM \`active_users\` WHERE \`id\` > ? ORDER BY \`id\` ASC LIMIT ?", [lastCursor, limit]);
    }
  }

  static listByOffset(exe: GenericExecutor, offset: number, limit: number): Promise<Active_usersRow[]> {
    return exe.query<Active_usersRow>("SELECT * FROM \`active_users\` ORDER BY \`id\` ASC LIMIT ? OFFSET ?", [limit, offset]);
  }
}
